# Curl Command for adding a new Dashboard record
curl --location 'http://localhost:8080/dashboards' \
--header 'Content-Type: application/json' \
--data '{
	"createdAt": "2022-01-01 12:25:30",
    "updatedAt": "2022-01-01 16:25:30",
    "title": "check running status"
}'

#Curl Command to get all Dashboard records
curl --location 'http://localhost:8080/dashboards'